#!/bin/bash
cd $(dirname $0)/..
echo
printf "ALL PODS UP: "
pods=$(./minislate kubectl get pods -n kube-system | tail -n +2)
while read -r line; do
	status=$(echo "$line" | awk '{print $3}')
	if [ "$status" != "Running" ]; then
		echo "FAIL"
		exit 1
	fi
done <<< "$pods"
echo "PASS"
