#!/bin/bash

expose() {
  IFS=':' read -ra PORTS <<< "$1"
  start-stop-daemon --oknodo --quiet --start --pidfile /var/run/socat-tcp-${PORTS[0]}.pid --background --make-pidfile --exec /usr/bin/socat -- -d -d -d -lf /var/log/socat-tcp-${PORTS[0]}.log TCP-LISTEN:${PORTS[0]},fork TCP:localhost:${PORTS[1]} < /dev/null
  start-stop-daemon --oknodo --quiet --start --pidfile /var/run/socat-udp-${PORTS[0]}.pid --background --make-pidfile --exec /usr/bin/socat -- -d -d -d -lf /var/log/socat-udp-${PORTS[0]}.log UDP4-RECVFROM:${PORTS[0]},fork UDP4-SENDTO:localhost:${PORTS[1]} < /dev/null
}

unexpose() {
  start-stop-daemon --oknodo --stop --quiet --pidfile /var/run/socat-tcp-$1.pid --exec /usr/bin/socat && rm -f /var/run/socat-tcp-$1.pid
  start-stop-daemon --oknodo --stop --quiet --pidfile /var/run/socat-udp-$1.pid --exec /usr/bin/socat && rm -f /var/run/socat-udp-$1.pid
}

if [[ $1 =~ ^(expose|unexpose)$ ]]; then
  "$@"
else
  echo "Invalid subcommand $1" >&2
  exit 1
fi
